clc;
clear all;
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\#Kuliah\#TA\#DATA\S1.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/09/09 12:46:21

%% Import the data
[~, ~, raw] = xlsread('D:\#Kuliah\#TA\#DATA\S1.xlsx','Sheet1','H3:K8762');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
S1 = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;